### ISSUE TITLE
"Emphasized" font results in "bold" font, what about italic font?

### ISSUE THREAD

**Issue by holtkamp** [star-micronics/star-cloudprnt-for-woocommerce#14]
Printing [emphasized text](https://github.com/star-micronics/star-cloudprnt-for-woocommerce/blob/2.1/dev_document_builder.md#set_text_emphasized), results in a **bold** font.

As a web developer I am used to the idea that the [HTML emphasis element ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em)`<em/>` results in _italic_ rendering of the font, so this was a small surprise for me 😉 

No problem, it is always good to learn. But this makes me wonder: is it also possible to have text printed in _italic_?

**Comment by gare-bear** [comment]
> But this makes me wonder: is it also possible to have text printed in _italic_?

No, unfortunately not. The Document Builder API leverages each printers native command set, but none of our printers support italic.
