### ISSUE TITLE
CloudPRNT - Support for HTTP Basic Auth

### ISSUE THREAD

**Issue by holtkamp** [star-micronics/star-cloudprnt-for-woocommerce#15]
_Since there is no repository dedicated to CloudPRNT protocol, I submit it here, feel free to move to the proper repository._ 

The documentation of the [CloudPRNT protocol](https://www.star-m.jp/products/s_print/CloudPRNTSDK/Documentation/en/developerguide/clientconfiguration.html) mentions the possibility to configure a user and a password:

>User (optional) - a user name that will be passed in the _first request body_ if specified.
Password (optional) - a password that will be specified in the first request body, if specified.

I was surprised the configured user and password:
- are passed in the first request body
- are apparently not used to support HTTP Basic Auth

HTTP Basic Auth which is often used as a first line of defence for accessing API endpoints, more information here:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization
- https://www.ibm.com/docs/SSGMCP_5.2.0/com.ibm.cics.ts.internet.doc/topics/dfhtl2a.html

Would it be an idea to use the user and password options to support HTTP Basic Auth as well?

**Comment by Lozrus** [comment]
@holtkamp The CloudPRNT user and password credentials should follow http basic auth, and should not be sent in the initial requests, only when challenged by the server with an appropriate 401 response. In fact honestly I have several requests that are completely opposite, from customers who are not used to http basic auth, and don't like the extra round trip that is required.

Are you raising this issue based on observed behaviour or on our documentation?

**Comment by holtkamp** [comment]
@Lozrus, thanks for the answer. 

>Are you raising this issue based on observed behaviour or on our documentation?

Well, on both... when no requests reached our servers when using Basic Auth, I dived into the documentation and concluded the `user` and `password` settings did not follow Basic Auth (which uses HTTP headers), but were used in the request _body_...

I checked it again and now it works, so it most probably was another misconfiguration, like reported  in https://github.com/star-micronics/star-cloudprnt-for-woocommerce/issues/16, or (if I remember correctly) something with the "Cipher Suites Encryption Level"

Conclusion: Basic Auth works indeed, it might be good to explicitly document this, to prevent similar issues in the future?

Closing issue.

**Comment by gare-bear** [comment]
@holtkamp We have explicit documentation on basic auth, mentioned [here](https://star-m.jp/products/s_print/CloudPRNTSDK/Documentation/en/developerguide/security.html), you might have missed it.

**Comment by holtkamp** [comment]
@gare-bear indeed, I missed that specific part, maybe:

1. a link can to https://star-m.jp/products/s_print/CloudPRNTSDK/Documentation/en/developerguide/security.html can be added on https://www.star-m.jp/products/s_print/CloudPRNTSDK/Documentation/en/developerguide/clientconfiguration.html and
2. omit "body" in the sentence "in the first request body"

It might also be an idea to put that documentation in a repository to allow pull requests with suggestions for improvements by the community / users like me... This has become quite common in the open source community the last years and allows to involve your customers to contribute 😉
