### ISSUE TITLE
add_two_columns_text_line when is more than one line

### ISSUE THREAD

**Issue by Rcor1** [star-micronics/star-cloudprnt-for-woocommerce#19]
Hi i try to split the the price on the right side how in the foto. 
i can do it with add_two_columns_text_line? 
the right data come always in a seperate line on the left side in a new line. 

![image](https://user-images.githubusercontent.com/21247506/159159735-02ed3ffc-ab53-48bb-885b-13d8f9bcf8c9.png)

**Comment by Lozrus** [comment]
@Rcor1 The current two_colums_text_line function doesn't handle word wrapping in the case that the columns can't all fit on a single line. Instead, I recommend that you format this yourself, use space characters to pad the line as you need and just output as text. If you check out source, you will see that the number of text columns available for your printer is provided (or you can just assume a 48 character with, if you will only use 80mm thermal models).
You will probably find the PHO wordwrap() function very useful too.
